server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #切换成nginx的8060端口
        server-addr: 192.168.0.111:8060
#        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'