server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #切换成nginx的8060端口
        server-addr: 10.0.2.111:8060
    #        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: 10.0.2.111:8858
        port: 8719
        client-ip: 10.0.2.213

management:
  endpoints:
    web:
      exposure:
        include: '*'