server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        #切换成nginx的8060端口
        server-addr: 10.0.2.111:8060
    #        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: 10.0.2.111:8858
        port: 8719
        client-ip: 10.0.2.213
      datasource:
        ds1:
          nacos:
            server-addr: 10.0.2.111:8060
            dataId: cloudalibaba-sentinel-service
            group: DEFAULT_GROUP
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'