server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 10.0.2.111:8060
    sentinel:
      transport:
        dashboard: 10.0.2.111:8858
        port: 8719
        client-ip: 10.0.2.213


management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true